# Generated by Django 4.2.20 on 2025-04-09 16:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money_balance',
            field=models.DecimalField(decimal_places=100, default=Decimal('0.00'), max_digits=1000, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Баланс'),
        ),
    ]
