# Generated by Django 4.2.20 on 2025-04-09 22:57

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_money_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='money_balance',
            field=models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=30, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Баланс'),
        ),
    ]
